trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pool:
  name: my-vm-pool     # 👈 Your own VM pool
  demands:
    - agent.name -equals myvm-agent

variables:
  imageName: 'myapp'
  acrName: 'teccitydemo.azurecr.io'
  tag: $(Build.BuildId)

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      displayName: Build frontend image
      inputs:
        command: build
        repository: $(acrName)/$(imageName)
        dockerfile: Dockerfile
        buildContext: .
        tags: |
          $(tag)
        containerRegistry: 'ACR-Registry-Connection'

    - task: Docker@2
      displayName: Push frontend image
      inputs:
        command: push
        repository: $(acrName)/$(imageName)
        tags: |
          $(tag)
        containerRegistry: 'ACR-Registry-Connection'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToWebApp
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to Web App
      inputs:
        azureSubscription: 'Azure-ARM-Connection'   # Your service connection
        appName: 'teccitydemo'                    # Same as created above
        imageName: 'teccitydemo.azurecr.io/myapp:$(tag)'

